#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i '/127.0.0.1\s\+localhost/s/127.0.0.1/127.0.0.2/' /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i '/facebook.com/s/.*/8.8.8.8\tfacebook.com/' /etc/hosts
else
    echo "8.8.8.8    facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi

echo "Changes applied. Don't forget to restore /etc/hosts if necessary."
