#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.

sudo cp /etc/hosts /etc/hosts.backup

sudo sed -i '/127.0.0.1[[:space:]]*localhost/c\127.0.0.2 localhost' /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i '/[[:space:]]*facebook.com/c\8.8.8.8 facebook.com' /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi

echo "Changes applied successfully. Don't forget to revert if this is a production environment."
